version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday

  - package-ecosystem: npm
    directory: /DEMO
    schedule:
      interval: weekly
      day: monday
