import { createRuleTester } from '../utils/eslint';

const error = (code: string): any => ({
  code,
  errors: [{ messageId: 'noChildren' }],
});

createRuleTester('on-children-in-void-element', {
  valid: [
    '<area />;',
    '<area></area>;',
    '<base />;',
    '<base></base>;',
    '<br />;',
    '<br></br>;',
    '<col />;',
    '<col></col>;',
    '<embed />;',
    '<embed></embed>;',
    '<hr />;',
    '<hr></hr>;',
    '<img />;',
    '<img></img>;',
    '<input />;',
    '<input></input>;',
    '<link />;',
    '<link></link>;',
    '<meta />;',
    '<meta></meta>;',
    '<param />;',
    '<param></param>;',
    '<source />;',
    '<source></source>;',
    '<track />;',
    '<track></track>;',
    '<wbr />;',
    '<wbr></wbr>;',
    '<div>Text</div>;',
    '<div children="foo" />;',
  ],
  invalid: [
    error('<area>foo</area>;'),
    error('<area children="foo" />;'),
    error('<area children={bar} />;'),
    error('<base>foo</base>;'),
    error('<base children="foo" />;'),
    error('<base children={bar} />;'),
    error('<br>foo</br>;'),
    error('<br children="foo" />;'),
    error('<br children={bar} />;'),
    error('<col>foo</col>;'),
    error('<col children="foo" />;'),
    error('<col children={bar} />;'),
    error('<embed>foo</embed>;'),
    error('<embed children="foo" />;'),
    error('<embed children={bar} />;'),
    error('<hr>foo</hr>;'),
    error('<hr children="foo" />;'),
    error('<hr children={bar} />;'),
    error('<img>foo</img>;'),
    error('<img children="foo" />;'),
    error('<img children={bar} />;'),
    error('<input>foo</input>;'),
    error('<input children="foo" />;'),
    error('<input children={bar} />;'),
    error('<link>foo</link>;'),
    error('<link children="foo" />;'),
    error('<link children={bar} />;'),
    error('<meta>foo</meta>;'),
    error('<meta children="foo" />;'),
    error('<meta children={bar} />;'),
    error('<param>foo</param>;'),
    error('<param children="foo" />;'),
    error('<param children={bar} />;'),
    error('<source>foo</source>;'),
    error('<source children="foo" />;'),
    error('<source children={bar} />;'),
    error('<track>foo</track>;'),
    error('<track children="foo" />;'),
    error('<track children={bar} />;'),
    error('<wbr>foo</wbr>;'),
    error('<wbr children="foo" />;'),
    error('<wbr children={bar} />;'),
  ],
});
