import { RuleTester } from 'eslint';
import { createRuleTester } from '../utils/eslint';

const error = (code: string, output: string): RuleTester.InvalidTestCase => ({
  code,
  output,
  errors: [{ messageId: 'preferAttribute' }],
});

createRuleTester('prefer-attributes-over-properties', {
  valid: [
    '<MyComponent className={foo} />;',
    '<div class={foo} />;',
    '<svg class={foo} />;',
    '<math class={foo} />;',
  ],
  invalid: [
    // HTML attributes
    error('<div className={foo} />;', '<div class={foo} />;'),
    error('<svg className={foo} />;', '<svg class={foo} />;'),
    error('<math className={foo} />;', '<math class={foo} />;'),
    error('<div className="foo" />;', '<div class="foo" />;'),
    error('<div acceptCharset="utf-8" />;', '<div accept-charset="utf-8" />;'),
    error('<div httpEquiv="refresh" />;', '<div http-equiv="refresh" />;'),
    error('<label htmlFor="input-id" />;', '<label for="input-id" />;'),
    // SVG attributes
    error('<rect accentHeight="10" />;', '<rect accent-height="10" />;'),
    error('<circle alignmentBaseline="middle" />;', '<circle alignment-baseline="middle" />;'),
    error('<g arabicForm="initial" />;', '<g arabic-form="initial" />;'),
    error('<path baselineShift="5" />;', '<path baseline-shift="5" />;'),
    error('<text capHeight="12" />;', '<text cap-height="12" />;'),
    error('<clipPath clipPath="url(#clip)" />;', '<clipPath clip-path="url(#clip)" />;'),
    error('<polygon clipRule="evenodd" />;', '<polygon clip-rule="evenodd" />;'),
    error('<linearGradient colorInterpolation="sRGB" />;', '<linearGradient color-interpolation="sRGB" />;'),
    error('<feFlood colorInterpolationFilters="linearRGB" />;', '<feFlood color-interpolation-filters="linearRGB" />;'),
    error('<feComponentTransfer colorProfile="profile" />;', '<feComponentTransfer color-profile="profile" />;'),
    error('<feGaussianBlur colorRendering="optimizeQuality" />;', '<feGaussianBlur color-rendering="optimizeQuality" />;'),
    error('<text dominantBaseline="central" />;', '<text dominant-baseline="central" />;'),
    error('<g enableBackground="new" />;', '<g enable-background="new" />;'),
    error('<path fillOpacity="0.5" />;', '<path fill-opacity="0.5" />;'),
    error('<polygon fillRule="evenodd" />;', '<polygon fill-rule="evenodd" />;'),
    error('<feFlood floodColor="#fff" />;', '<feFlood flood-color="#fff" />;'),
    error('<feFlood floodOpacity="0.7" />;', '<feFlood flood-opacity="0.7" />;'),
    error('<text fontFamily="Arial" />;', '<text font-family="Arial" />;'),
    error('<text fontSize="16" />;', '<text font-size="16" />;'),
    error('<text fontSizeAdjust="0.5" />;', '<text font-size-adjust="0.5" />;'),
    error('<text fontStretch="condensed" />;', '<text font-stretch="condensed" />;'),
    error('<text fontStyle="italic" />;', '<text font-style="italic" />;'),
    error('<text fontVariant="small-caps" />;', '<text font-variant="small-caps" />;'),
    error('<text fontWeight="bold" />;', '<text font-weight="bold" />;'),
    error('<glyph glyphName="glyph" />;', '<glyph glyph-name="glyph" />;'),
    error('<glyph glyphOrientationHorizontal="0" />;', '<glyph glyph-orientation-horizontal="0" />;'),
    error('<glyph glyphOrientationVertical="90" />;', '<glyph glyph-orientation-vertical="90" />;'),
    error('<font horizAdvX="100" />;', '<font horiz-adv-x="100" />;'),
    error('<font horizOriginX="0" />;', '<font horiz-origin-x="0" />;'),
    error('<image imageRendering="optimizeSpeed" />;', '<image image-rendering="optimizeSpeed" />;'),
    error('<text letterSpacing="2" />;', '<text letter-spacing="2" />;'),
    error('<feDiffuseLighting lightingColor="#000" />;', '<feDiffuseLighting lighting-color="#000" />;'),
    error('<marker markerEnd="url(#end)" />;', '<marker marker-end="url(#end)" />;'),
    error('<marker markerMid="url(#mid)" />;', '<marker marker-mid="url(#mid)" />;'),
    error('<marker markerStart="url(#start)" />;', '<marker marker-start="url(#start)" />;'),
    error('<font overlinePosition="5" />;', '<font overline-position="5" />;'),
    error('<font overlineThickness="1" />;', '<font overline-thickness="1" />;'),
    error('<g paintOrder="stroke" />;', '<g paint-order="stroke" />;'),
    error('<font panose1="2 11 6 4 2 2 2 2 2 4" />;', '<font panose-1="2 11 6 4 2 2 2 2 2 4" />;'),
    error('<g pointerEvents="none" />;', '<g pointer-events="none" />;'),
    error('<image renderingIntent="auto" />;', '<image rendering-intent="auto" />;'),
    error('<rect shapeRendering="crispEdges" />;', '<rect shape-rendering="crispEdges" />;'),
    error('<stop stopColor="#fff" />;', '<stop stop-color="#fff" />;'),
    error('<stop stopOpacity="0.5" />;', '<stop stop-opacity="0.5" />;'),
    error('<font strikethroughPosition="2" />;', '<font strikethrough-position="2" />;'),
    error('<font strikethroughThickness="1" />;', '<font strikethrough-thickness="1" />;'),
    error('<path strokeDasharray="5,5" />;', '<path stroke-dasharray="5,5" />;'),
    error('<path strokeDashoffset="2" />;', '<path stroke-dashoffset="2" />;'),
    error('<path strokeLinecap="round" />;', '<path stroke-linecap="round" />;'),
    error('<path strokeLinejoin="bevel" />;', '<path stroke-linejoin="bevel" />;'),
    error('<path strokeMiterlimit="4" />;', '<path stroke-miterlimit="4" />;'),
    error('<path strokeOpacity="0.8" />;', '<path stroke-opacity="0.8" />;'),
    error('<path strokeWidth="3" />;', '<path stroke-width="3" />;'),
    error('<text textAnchor="middle" />;', '<text text-anchor="middle" />;'),
    error('<text textDecoration="underline" />;', '<text text-decoration="underline" />;'),
    error('<text textRendering="geometricPrecision" />;', '<text text-rendering="geometricPrecision" />;'),
    error('<font underlinePosition="1" />;', '<font underline-position="1" />;'),
    error('<font underlineThickness="2" />;', '<font underline-thickness="2" />;'),
    error('<text unicodeBidi="embed" />;', '<text unicode-bidi="embed" />;'),
    error('<font unicodeRange="U+0020-007F" />;', '<font unicode-range="U+0020-007F" />;'),
    error('<font unitsPerEm="1000" />;', '<font units-per-em="1000" />;'),
    error('<font vAlphabetic="10" />;', '<font v-alphabetic="10" />;'),
    error('<font vHanging="5" />;', '<font v-hanging="5" />;'),
    error('<font vIdeographic="3" />;', '<font v-ideographic="3" />;'),
    error('<font vMathematical="7" />;', '<font v-mathematical="7" />;'),
    error('<path vectorEffect="non-scaling-stroke" />;', '<path vector-effect="non-scaling-stroke" />;'),
    error('<font vertAdvY="100" />;', '<font vert-adv-y="100" />;'),
    error('<font vertOriginX="0" />;', '<font vert-origin-x="0" />;'),
    error('<font vertOriginY="0" />;', '<font vert-origin-y="0" />;'),
    error('<text wordSpacing="4" />;', '<text word-spacing="4" />;'),
    error('<text writingMode="tb" />;', '<text writing-mode="tb" />;'),
    error('<font xHeight="8" />;', '<font x-height="8" />;'),
    error('<a xlinkActuate="onLoad" />;', '<a xlink:actuate="onLoad" />;'),
    error('<a xlinkArcrole="arcrole" />;', '<a xlink:arcrole="arcrole" />;'),
    error('<a xlinkHref="foo.svg" />;', '<a href="foo.svg" />;'),
    error('<a xlinkRole="role" />;', '<a xlink:role="role" />;'),
    error('<a xlinkShow="new" />;', '<a xlink:show="new" />;'),
    error('<a xlinkTitle="title" />;', '<a xlink:title="title" />;'),
    error('<a xlinkType="simple" />;', '<a xlink:type="simple" />;'),
    error('<svg xmlBase="base" />;', '<svg xml:base="base" />;'),
    error('<svg xmlLang="en" />;', '<svg xml:lang="en" />;'),
    error('<svg xmlSpace="preserve" />;', '<svg xml:space="preserve" />;'),
  ],
});
