<maction actiontype="toggle" selection="1" />;
<menclose notation="string" />;
<mfenced open="{" close="}" separators=";;,"/>;
<mfrac denomalign="right" numalign="left" linethickness="" />;
<mi mathvariant="normal" />;
<mmultiscripts subscriptshift="1%" superscriptshift="1%" />;
<mo symmetric="true" largeop="false" />;
<mover accent="false" />;
<mpadded depth="1" width="1" />;
<ms lquote="„" rquote="'">abc</ms>;
<mstyle background="black" color="white" fontsize="1.1" fontweight="inherit" />;
<msub subscriptshift="1%"> base subscript </msub>;
<msubsup subscriptshift="1%" superscriptshift="1%" />;
<msup superscriptshift="1%" />;
<mtable frame="solid" rowlines="solid" align="axis 3" />;
<mtd columnspan={1} rowspan="2" />;
<mtr columnalign="left" rowalign="top" />;
