name: Dependabot DEMO

on:
  push:
    branches:
      - 'dependabot/npm_and_yarn/DEMO/**'

defaults:
  run:
    working-directory: ./DEMO

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: npm

    - run: npm ci
    - run: npm run build
