name: Tests

on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v6

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 22
        cache: npm

    - run: npm ci --legacy-peer-deps
    - run: npm run types
    - run: npm run build
    - run: npm run lint
    - run: npm test
    - run: npm run size
